name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Ensures latest node version
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use Node.js 16 or higher

    - name: Generate snake.svg
      uses: Platane/snk@v3.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output: dist/snake.svg

    - name: Push generated snake.svg to main branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dist/snake.svg
        git commit -m "Generated snake.svg"
        git push origin main
